# Generated by Django 5.2.1 on 2025-11-19 11:57

import api.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='0.0', help_text="Version number, e.g., '1.0' or '2025-11-01'", max_length=20, unique=True)),
                ('content_md', models.TextField(blank=True, default='', help_text='Markdown content of the terms')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, help_text='Optional unique username used for legacy flows.', max_length=150, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('avatar_url', models.CharField(blank=True, help_text='URL to user avatar image', max_length=500, null=True)),
                ('account_type', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('pro_plus', 'Pro+')], default='free', max_length=10)),
                ('source_tag', models.CharField(choices=[('JACEK', 'Jacek Campaign'), ('WEB', 'Organic Web')], default='WEB', max_length=10)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='User preferences: {"theme": {"mode": "dark", "themeId": "studio"}, "calendar": {"operating_start_hour": 6, "operating_end_hour": 22}}')),
                ('terms_agreement_date', models.DateTimeField(blank=True, help_text='When the user accepted the ToS', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('terms_agreement', models.ForeignKey(blank=True, help_text='The ToS version this user has accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreed_users', to='api.termsofservice')),
            ],
            options={
                'verbose_name': 'Platform user',
                'verbose_name_plural': 'Platform users',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500, unique=True)),
                ('file_url', models.CharField(max_length=500, unique=True)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=16)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes of the stored media file')),
                ('storage_bucket', models.CharField(blank=True, default='', help_text='Supabase bucket name (if applicable)', max_length=100)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('achievement', 'Achievement'), ('cancellation', 'Cancellation'), ('group_full', 'Group Full'), ('other', 'Other')], default='other', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('color_index', models.IntegerField(default=0, help_text='Index of the site color in the palette (0-11)')),
                ('team_size', models.IntegerField(default=1, help_text='Cached count of team members for calendar optimization')),
                ('is_mock', models.BooleanField(default=False, help_text='Flag indicating if this is a mock/demo site for testing (includes showcase)')),
                ('template_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('avatar', 'Avatar'), ('site_content', 'Site content')], max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='api.mediaasset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_usages', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_usages', to='api.site')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('event_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_owner', models.ForeignKey(blank=True, help_text='Owner assigned to this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_events', to=settings.AUTH_USER_MODEL)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events', to='api.client')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.site')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='CustomReactComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('source_code', models.TextField(blank=True, help_text='Oryginalny kod JSX dla celów edycji')),
                ('compiled_js', models.FileField(blank=True, null=True, upload_to=api.models.custom_component_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this component', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_components', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(help_text='Site this custom component belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_components', to='api.site')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.site'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.event')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.site')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Dostępny', max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_length', models.IntegerField(default=60, help_text='Meeting duration in minutes (e.g., 30, 45, 60)')),
                ('time_snapping', models.IntegerField(default=30, help_text='Interval in minutes for when meetings can start (e.g., 15, 30, 60)')),
                ('buffer_time', models.IntegerField(default=0, help_text='Minimum time between meetings in minutes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_availability_blocks', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='api.site')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SiteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('template_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('change_summary', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_site_versions', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, help_text='Required for sending invitations', max_length=254, null=True)),
                ('role_description', models.CharField(blank=True, help_text='E.g., "Yoga Instructor", "Therapist"', max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Member bio for public display')),
                ('avatar_url', models.CharField(blank=True, help_text='Custom avatar URL or null for generated', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invitation_status', models.CharField(choices=[('mock', 'Mock (Not invited)'), ('invited', 'Invited (No account)'), ('pending', 'Pending (Has account)'), ('linked', 'Linked (Connected)'), ('rejected', 'Rejected/Left')], default='mock', max_length=16)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('permission_role', models.CharField(choices=[('viewer', 'Viewer'), ('contributor', 'Contributor'), ('manager', 'Manager')], default='viewer', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='api.site')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='assigned_to_team_member',
            field=models.ForeignKey(blank=True, help_text='Team member assigned to this event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_events', to='api.teammember'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('template_config', models.JSONField(default=dict)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name for display', max_length=255)),
                ('slug', models.SlugField(help_text='Unique identifier for the template', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('booking_cancellation', 'Booking Cancellation'), ('account_registration', 'Account Registration'), ('site_status', 'Site Status'), ('plan_change', 'Plan Change'), ('subscription_reminder', 'Subscription Reminder')], help_text='Template category', max_length=50)),
                ('subject_pl', models.CharField(help_text='Email subject in Polish', max_length=255)),
                ('subject_en', models.CharField(help_text='Email subject in English', max_length=255)),
                ('content_pl', models.TextField(help_text='HTML email content in Polish')),
                ('content_en', models.TextField(help_text='HTML email content in English')),
                ('is_default', models.BooleanField(default=False, help_text='Is this a default system template?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of custom template (null for default templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', '-is_default', 'name'],
                'indexes': [models.Index(fields=['owner', 'category'], name='api_emailte_owner_i_7327e9_idx'), models.Index(fields=['slug'], name='api_emailte_slug_f862f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('password_reset', 'Password Reset')], default='login', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User associated with this magic link', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action_type'], name='api_magicli_user_id_167e02_idx'), models.Index(fields=['user', 'used'], name='api_magicli_user_id_12d77a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['media_type'], name='api_mediaas_media_t_b488c2_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['uploaded_at'], name='api_mediaas_uploade_4e60c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediausage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('site__isnull', False), ('user__isnull', True)), models.Q(('site__isnull', True), ('user__isnull', False)), _connector='OR'), name='mediausage_single_context'),
        ),
        migrations.AddConstraint(
            model_name='mediausage',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('asset', 'site', 'usage_type'), name='mediausage_unique_site_usage'),
        ),
        migrations.AddConstraint(
            model_name='mediausage',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('asset', 'user', 'usage_type'), name='mediausage_unique_user_usage'),
        ),
        migrations.AddIndex(
            model_name='customreactcomponent',
            index=models.Index(fields=['site'], name='api_customr_site_id_83ae73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customreactcomponent',
            unique_together={('site', 'name')},
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['site', 'email'], name='api_client_site_id_093739_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['site', 'google_id'], name='api_client_site_id_3ff701_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('site', 'email')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['site'], name='api_booking_site_id_26abc3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['event'], name='api_booking_event_i_6d6f2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityblock',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='availability_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='siteversion',
            constraint=models.UniqueConstraint(fields=('site', 'version_number'), name='unique_site_version_per_site'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['site', 'linked_user'], name='api_teammem_site_id_04cb88_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['invitation_token'], name='api_teammem_invitat_274d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['email'], name='api_teammem_email_fc2829_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='event_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_to_owner__isnull', True), ('assigned_to_team_member__isnull', False)), models.Q(('assigned_to_owner__isnull', False), ('assigned_to_team_member__isnull', True)), _connector='OR'), name='event_single_assignment'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['owner'], name='api_templat_owner_i_18624c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('owner', 'name')},
        ),
    ]
