# Generated by Django 5.2.1 on 2025-11-27 15:05

import api.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmation_token', models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True)),
                ('unsubscribe_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('emails_sent', models.IntegerField(default=0)),
                ('emails_opened', models.IntegerField(default=0)),
                ('emails_clicked', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='0.0', help_text="Version number, e.g., '1.0' or '2025-11-01'", max_length=20, unique=True)),
                ('content_md', models.TextField(blank=True, default='', help_text='Markdown content of the terms')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, help_text='Optional unique username used for legacy flows.', max_length=150, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('avatar_url', models.CharField(blank=True, help_text='URL to user avatar image', max_length=500, null=True)),
                ('public_image_url', models.CharField(blank=True, help_text='Public image URL displayed on team page', max_length=500, null=True)),
                ('role_description', models.CharField(blank=True, help_text='Role/title displayed on team page (e.g., "Założyciel", "Instruktor")', max_length=200, null=True)),
                ('account_type', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('pro_plus', 'Pro+')], default='free', max_length=10)),
                ('source_tag', models.CharField(choices=[('JACEK', 'Jacek Campaign'), ('WEB', 'Organic Web'), ('TEAM_INV', 'Team Invitation')], default='WEB', max_length=10)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='User preferences: {"theme": {"mode": "dark", "themeId": "studio"}, "calendar": {"operating_start_hour": 6, "operating_end_hour": 22}}')),
                ('terms_agreement_date', models.DateTimeField(blank=True, help_text='When the user accepted the ToS', null=True)),
                ('is_temporary_password', models.BooleanField(default=False, help_text='Whether the user has a temporary password that must be changed')),
                ('password_changed_at', models.DateTimeField(blank=True, help_text='When the user last changed their password', null=True)),
                ('daily_image_searches', models.IntegerField(default=0, help_text='Number of Pexels searches performed today')),
                ('last_search_date', models.DateField(blank=True, help_text='Date of last Pexels search (for daily reset)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('terms_agreement', models.ForeignKey(blank=True, help_text='The ToS version this user has accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreed_users', to='api.termsofservice')),
            ],
            options={
                'verbose_name': 'Platform user',
                'verbose_name_plural': 'Platform users',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_type', models.CharField(choices=[('studio_editor', 'Studio Editor'), ('studio_events', 'Studio Events'), ('studio_dashboard', 'Studio Dashboard'), ('studio_team', 'Studio Team'), ('other', 'Other')], default='studio_editor', help_text='Context/section where this agent operates', max_length=50)),
                ('name', models.CharField(help_text='Agent name (e.g., "Asystent #1", "Events Helper")', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this agent', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500, unique=True)),
                ('file_url', models.CharField(max_length=500, unique=True)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('other', 'Other')], default='other', max_length=16)),
                ('file_size', models.BigIntegerField(default=0, help_text='Size in bytes of the stored media file')),
                ('storage_bucket', models.CharField(blank=True, default='', help_text='Supabase bucket name (if applicable)', max_length=100)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='api.newslettersubscription')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('achievement', 'Achievement'), ('cancellation', 'Cancellation'), ('group_full', 'Group Full'), ('other', 'Other')], default='other', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session ID for this transaction (order ID)', max_length=100, unique=True)),
                ('amount', models.IntegerField(help_text='Amount in grosz (1 PLN = 100 grosz)')),
                ('currency', models.CharField(default='PLN', help_text='Currency code (ISO 4217)', max_length=3)),
                ('description', models.CharField(help_text='Payment description', max_length=255)),
                ('email', models.EmailField(help_text='Customer email', max_length=254)),
                ('plan_id', models.CharField(blank=True, help_text='Plan ID being purchased (free, pro, pro-plus)', max_length=50, null=True)),
                ('token', models.CharField(blank=True, help_text='Payment token from Przelewy24', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current payment status', max_length=20)),
                ('p24_order_id', models.CharField(blank=True, help_text='Przelewy24 order ID (returned after payment)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('subdomain', models.CharField(blank=True, editable=False, help_text='Auto-generated subdomain (e.g., 1234-nazwa.youreasysite.pl)', max_length=255, null=True, unique=True)),
                ('is_published', models.BooleanField(default=False, help_text='Whether this site is published and publicly accessible')),
                ('published_at', models.DateTimeField(blank=True, help_text='When the site was first published', null=True)),
                ('color_index', models.IntegerField(default=0, help_text='Index of the site color in the palette (0-11)')),
                ('team_size', models.IntegerField(default=1, help_text='Cached count of team members for calendar optimization')),
                ('is_mock', models.BooleanField(default=False, help_text='Flag indicating if this is a mock/demo site for testing (includes showcase)')),
                ('template_config', models.JSONField(blank=True, default=dict)),
                ('ai_checkpoints', models.JSONField(blank=True, default=list, help_text='List of AI checkpoints with {id, timestamp, config, message} for undo functionality')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscriptions', to='api.site'),
        ),
        migrations.CreateModel(
            name='MediaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('avatar', 'Avatar'), ('site_content', 'Site content')], max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='api.mediaasset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_usages', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_usages', to='api.site')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.EmailField(help_text='Google account email', max_length=254)),
                ('access_token', models.TextField(help_text='OAuth access token (encrypted)')),
                ('refresh_token', models.TextField(help_text='OAuth refresh token (encrypted)')),
                ('token_expires_at', models.DateTimeField(help_text='When the access token expires')),
                ('calendar_id', models.CharField(help_text='Google Calendar ID (usually the email)', max_length=255)),
                ('calendar_name', models.CharField(blank=True, help_text='Display name of the calendar', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether sync is currently active')),
                ('sync_enabled', models.BooleanField(default=True, help_text='Whether to sync events to Google Calendar')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, help_text='User who connected this Google Calendar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_google_calendars', to=settings.AUTH_USER_MODEL)),
                ('site', models.OneToOneField(help_text='Site connected to Google Calendar', on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_integration', to='api.site')),
            ],
            options={
                'verbose_name': 'Google Calendar Integration',
                'verbose_name_plural': 'Google Calendar Integrations',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('capacity', models.IntegerField(default=1, help_text='Maximum capacity. Use -1 for unlimited participants.')),
                ('event_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], default='individual', max_length=32)),
                ('show_host', models.BooleanField(default=False, help_text='Whether to display the host/assigned person publicly')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_owner', models.ForeignKey(blank=True, help_text='Owner assigned to this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_events', to=settings.AUTH_USER_MODEL)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events', to='api.client')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.site')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='DomainOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='Full domain name (e.g., example.com)', max_length=255)),
                ('ovh_order_id', models.CharField(blank=True, help_text='OVH order ID from the API', max_length=255, null=True)),
                ('ovh_cart_id', models.CharField(blank=True, help_text='OVH cart ID used for this order', max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Domain price in EUR', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('free', 'Added to Cloudflare - Awaiting Configuration'), ('pending', 'Waiting for Nameserver Propagation'), ('pending_payment', 'Pending Payment'), ('configuring_dns', 'Configuring DNS'), ('active', 'Active'), ('dns_error', 'DNS Configuration Error'), ('expired', 'Expired (Not Configured in Time)'), ('cancelled', 'Cancelled'), ('error', 'Configuration Error')], default='pending_payment', help_text='Current status of the domain order', max_length=32)),
                ('payment_url', models.URLField(blank=True, help_text='Mock payment URL for testing', null=True)),
                ('dns_configuration', models.JSONField(blank=True, default=dict, help_text='DNS records configured for this domain')),
                ('target', models.CharField(blank=True, help_text='Target URL for domain redirect (e.g., youtube.com or user site subdomain)', max_length=255, null=True)),
                ('proxy_mode', models.BooleanField(default=False, help_text='If True, use reverse proxy (keeps URL). If False, use 301 redirect (changes URL)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if DNS configuration failed', null=True)),
                ('cloudflare_zone_id', models.CharField(blank=True, help_text='Cloudflare Zone ID for this domain', max_length=255, null=True)),
                ('cloudflare_nameservers', models.JSONField(blank=True, default=list, help_text='Cloudflare nameservers assigned to this domain')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration time for domain reservation (48h from creation if not configured)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='domain_orders', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, help_text='Site this domain is for (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_orders', to='api.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomReactComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('source_code', models.TextField(blank=True, help_text='Oryginalny kod JSX dla celów edycji')),
                ('compiled_js', models.FileField(blank=True, null=True, upload_to=api.models.custom_component_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this component', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_components', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(help_text='Site this custom component belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='custom_components', to='api.site')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.site'),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('studio_editor', 'Studio Editor'), ('studio_events', 'Studio Events'), ('studio_dashboard', 'Studio Dashboard'), ('studio_team', 'Studio Team'), ('other', 'Other')], default='studio_editor', help_text='Context/section where the message was sent', max_length=50)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context data (page_id, module_id, etc.)')),
                ('user_message', models.TextField(help_text='Message sent by the user')),
                ('ai_response', models.TextField(help_text='Response from AI assistant')),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID for tracking', max_length=100, null=True)),
                ('status', models.CharField(default='success', help_text='Status of the AI response (success, error, clarification)', max_length=20)),
                ('deleted', models.BooleanField(default=False, help_text='Whether this message was deleted/reverted by user')),
                ('related_event_id', models.IntegerField(blank=True, help_text='ID of BigEvent created/modified by this AI response (for undo functionality)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Agent that handled this conversation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='api.agent')),
                ('user', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, help_text='Site context for the message (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='api.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.client')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.event')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.site')),
            ],
        ),
        migrations.CreateModel(
            name='BigEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_participants', models.IntegerField(help_text='Maximum number of participants')),
                ('current_participants', models.IntegerField(default=0, help_text='Current number of registered participants')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price per person', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('email_sent', models.BooleanField(default=False, help_text='Whether email has been sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, help_text='Event cover image', max_length=500, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional event details (schedule, requirements, etc.)')),
                ('ai_checkpoints', models.JSONField(blank=True, default=list, help_text='List of AI checkpoints (max 20, newest first). Each checkpoint stores event state before AI changes.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_big_events', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='big_events', to='api.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this agent is working on (optional for global agents)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='api.site'),
        ),
        migrations.CreateModel(
            name='SiteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('template_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('change_summary', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_site_versions', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', help_text='Full name of the team member', max_length=300)),
                ('email', models.EmailField(blank=True, help_text='Required for sending invitations', max_length=254, null=True)),
                ('role_description', models.CharField(blank=True, help_text='E.g., "Yoga Instructor", "Therapist"', max_length=255)),
                ('avatar_url', models.CharField(blank=True, help_text='Avatar URL for display', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invitation_status', models.CharField(choices=[('mock', 'Mock (Not invited)'), ('invited', 'Invited (No account)'), ('pending', 'Pending (Has account)'), ('linked', 'Linked (Connected)'), ('rejected', 'Rejected/Left')], default='mock', max_length=16)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('permission_role', models.CharField(choices=[('viewer', 'Viewer'), ('contributor', 'Contributor'), ('manager', 'Manager')], default='viewer', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='api.site')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('action_type', models.CharField(choices=[('login', 'Login'), ('password_reset', 'Password Reset'), ('team_invitation', 'Team Invitation')], default='login', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User associated with this magic link', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to=settings.AUTH_USER_MODEL)),
                ('team_member', models.ForeignKey(blank=True, help_text='Team member associated with this invitation link', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_links', to='api.teammember')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='assigned_to_team_member',
            field=models.ForeignKey(blank=True, help_text='Team member assigned to this event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_events', to='api.teammember'),
        ),
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Dostępny', max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_length', models.IntegerField(default=60, help_text='Meeting duration in minutes (e.g., 30, 45, 60)')),
                ('time_snapping', models.IntegerField(default=30, help_text='Interval in minutes for when meetings can start (e.g., 15, 30, 60)')),
                ('buffer_time', models.IntegerField(default=0, help_text='Minimum time between meetings in minutes')),
                ('show_host', models.BooleanField(default=False, help_text='Whether to display the host/assigned person publicly')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_owner', models.ForeignKey(blank=True, help_text='Owner assigned to this availability block', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_availability_blocks', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_availability_blocks', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_blocks', to='api.site')),
                ('assigned_to_team_member', models.ForeignKey(blank=True, help_text='Team member assigned to this availability block', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_availability_blocks', to='api.teammember')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_type', models.CharField(choices=[('owner', 'Owner'), ('team_member', 'Team Member')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='event_snapshot', max_length=32)),
                ('host_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_sessions', to='api.event')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attended_sessions', to='api.site')),
                ('host_team_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_sessions', to='api.teammember')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('template_config', models.JSONField(default=dict)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Name of the person leaving the testimonial', max_length=255)),
                ('author_email', models.EmailField(blank=True, help_text='Email address (optional, for verification)', max_length=254, null=True)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5')),
                ('content', models.TextField(help_text='Testimonial content')),
                ('is_approved', models.BooleanField(default=True, help_text='Whether this testimonial is approved for public display')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(help_text='Site this testimonial belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='api.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='AI-generated summary of recent testimonials')),
                ('detailed_summary', models.TextField(blank=True, help_text='Detailed AI-generated analysis for admin panel')),
                ('total_count', models.IntegerField(default=0, help_text='Total number of testimonials analyzed')),
                ('average_rating', models.FloatField(default=0.0, help_text='Average rating from analyzed testimonials')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(help_text='Site this summary belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_summary', to='api.site')),
            ],
            options={
                'verbose_name_plural': 'Testimonial summaries',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name for display', max_length=255)),
                ('slug', models.SlugField(help_text='Unique identifier for the template', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('session_cancelled_by_creator', 'Session Cancelled by Creator'), ('dev', 'Development/Testing')], help_text='Template category', max_length=50)),
                ('subject_pl', models.CharField(help_text='Email subject in Polish', max_length=255)),
                ('subject_en', models.CharField(help_text='Email subject in English', max_length=255)),
                ('content_pl', models.TextField(help_text='HTML email content in Polish')),
                ('content_en', models.TextField(help_text='HTML email content in English')),
                ('is_default', models.BooleanField(default=False, help_text='Is this a default system template?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of custom template (null for default templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', '-is_default', 'name'],
                'indexes': [models.Index(fields=['owner', 'category'], name='api_emailte_owner_i_7327e9_idx'), models.Index(fields=['slug'], name='api_emailte_slug_f862f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(help_text='Google Calendar event ID', max_length=255)),
                ('last_synced_at', models.DateTimeField(auto_now=True, help_text='Last sync timestamp')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.OneToOneField(help_text='Local event', on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_event', to='api.event')),
                ('integration', models.ForeignKey(help_text='Google Calendar integration', on_delete=django.db.models.deletion.CASCADE, related_name='synced_events', to='api.googlecalendarintegration')),
            ],
            options={
                'verbose_name': 'Google Calendar Event',
                'verbose_name_plural': 'Google Calendar Events',
                'indexes': [models.Index(fields=['integration', 'google_event_id'], name='api_googlec_integra_4eb0b8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['media_type'], name='api_mediaas_media_t_b488c2_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['uploaded_at'], name='api_mediaas_uploade_4e60c9_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletteranalytics',
            index=models.Index(fields=['tracking_token'], name='api_newslet_trackin_a71651_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletteranalytics',
            index=models.Index(fields=['subscription', 'sent_at'], name='api_newslet_subscri_17368c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='api_payment_user_id_bab04b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['session_id'], name='api_payment_session_9cfe35_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='api_payment_status_c61efc_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['site', 'is_active'], name='api_newslet_site_id_098b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['unsubscribe_token'], name='api_newslet_unsubsc_caab5d_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['confirmation_token'], name='api_newslet_confirm_6c4238_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='newslettersubscription',
            unique_together={('site', 'email')},
        ),
        migrations.AddConstraint(
            model_name='mediausage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('site__isnull', False), ('user__isnull', True)), models.Q(('site__isnull', True), ('user__isnull', False)), _connector='OR'), name='mediausage_single_context'),
        ),
        migrations.AddConstraint(
            model_name='mediausage',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('asset', 'site', 'usage_type'), name='mediausage_unique_site_usage'),
        ),
        migrations.AddConstraint(
            model_name='mediausage',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('asset', 'user', 'usage_type'), name='mediausage_unique_user_usage'),
        ),
        migrations.AddIndex(
            model_name='googlecalendarintegration',
            index=models.Index(fields=['site', 'is_active'], name='api_googlec_site_id_3e77cf_idx'),
        ),
        migrations.AddIndex(
            model_name='domainorder',
            index=models.Index(fields=['user', 'status'], name='api_domaino_user_id_8076ca_idx'),
        ),
        migrations.AddIndex(
            model_name='domainorder',
            index=models.Index(fields=['site'], name='api_domaino_site_id_e7d8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='domainorder',
            index=models.Index(fields=['ovh_order_id'], name='api_domaino_ovh_ord_285d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='domainorder',
            index=models.Index(fields=['domain_name'], name='api_domaino_domain__720902_idx'),
        ),
        migrations.AddIndex(
            model_name='domainorder',
            index=models.Index(fields=['expires_at'], name='api_domaino_expires_528b93_idx'),
        ),
        migrations.AddConstraint(
            model_name='domainorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['free', 'pending', 'configuring_dns', 'active'])), fields=('domain_name',), name='unique_active_domain_per_system'),
        ),
        migrations.AddIndex(
            model_name='customreactcomponent',
            index=models.Index(fields=['site'], name='api_customr_site_id_83ae73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customreactcomponent',
            unique_together={('site', 'name')},
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['site', 'email'], name='api_client_site_id_093739_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['site', 'google_id'], name='api_client_site_id_3ff701_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('site', 'email')},
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['agent', '-created_at'], name='api_chathis_agent_i_8dfb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['user', '-created_at'], name='api_chathis_user_id_b3b27a_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['site', '-created_at'], name='api_chathis_site_id_b364be_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['context_type', '-created_at'], name='api_chathis_context_2bcf35_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['site'], name='api_booking_site_id_26abc3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['event'], name='api_booking_event_i_6d6f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='bigevent',
            index=models.Index(fields=['site', 'status'], name='api_bigeven_site_id_adb6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='bigevent',
            index=models.Index(fields=['-created_at'], name='api_bigeven_created_9a2263_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['user', 'site', 'context_type'], name='api_agent_user_id_333fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['user', '-created_at'], name='api_agent_user_id_96b225_idx'),
        ),
        migrations.AddConstraint(
            model_name='siteversion',
            constraint=models.UniqueConstraint(fields=('site', 'version_number'), name='unique_site_version_per_site'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['site', 'linked_user'], name='api_teammem_site_id_04cb88_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['invitation_token'], name='api_teammem_invitat_274d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['email'], name='api_teammem_email_fc2829_idx'),
        ),
        migrations.AddIndex(
            model_name='magiclink',
            index=models.Index(fields=['user', 'action_type'], name='api_magicli_user_id_167e02_idx'),
        ),
        migrations.AddIndex(
            model_name='magiclink',
            index=models.Index(fields=['user', 'used'], name='api_magicli_user_id_12d77a_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1), ('capacity', -1), _connector='OR'), name='event_capacity_positive_or_unlimited'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_to_owner__isnull', True), ('assigned_to_team_member__isnull', False)), models.Q(('assigned_to_owner__isnull', False), ('assigned_to_team_member__isnull', True)), _connector='OR'), name='event_single_assignment'),
        ),
        migrations.AddConstraint(
            model_name='availabilityblock',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='availability_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='availabilityblock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_to_owner__isnull', True), ('assigned_to_team_member__isnull', True)), models.Q(('assigned_to_owner__isnull', True), ('assigned_to_team_member__isnull', False)), models.Q(('assigned_to_owner__isnull', False), ('assigned_to_team_member__isnull', True)), _connector='OR'), name='availability_optional_single_assignment'),
        ),
        migrations.AddIndex(
            model_name='attendedsession',
            index=models.Index(fields=['site', 'host_type'], name='api_attende_site_id_6b10e2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendedsession',
            index=models.Index(fields=['start_time'], name='api_attende_start_t_09867f_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendedsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('host_type', 'owner'), ('host_user__isnull', False), ('host_team_member__isnull', True)), models.Q(('host_type', 'team_member'), ('host_team_member__isnull', False), ('host_user__isnull', True)), _connector='OR'), name='attendedsession_host_guard'),
        ),
        migrations.AddConstraint(
            model_name='attendedsession',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 1)), name='attendedsession_positive_duration'),
        ),
        migrations.AddConstraint(
            model_name='attendedsession',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False), ('host_type', 'owner'), ('host_user__isnull', False)), fields=('event', 'host_user'), name='unique_attendance_owner_per_event'),
        ),
        migrations.AddConstraint(
            model_name='attendedsession',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False), ('host_team_member__isnull', False), ('host_type', 'team_member')), fields=('event', 'host_team_member'), name='unique_attendance_member_per_event'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['owner'], name='api_templat_owner_i_18624c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['site', 'is_approved'], name='api_testimo_site_id_a73bd6_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['site', 'rating'], name='api_testimo_site_id_b049c6_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['created_at'], name='api_testimo_created_73c6da_idx'),
        ),
        migrations.AddConstraint(
            model_name='testimonial',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='testimonial_rating_range'),
        ),
    ]
