# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_mock',
            field=models.BooleanField(default=False, help_text='Flag indicating if this is a mock/demo site for testing'),
        ),
    ]
