# Generated by Django 5.2.1 on 2025-11-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User preferences including calendar settings (operating_start_hour, operating_end_hour)'),
        ),
    ]
