# Generated by Django 5.2.1 on 2025-01-21 12:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='The domain name being ordered', max_length=255)),
                ('ovh_order_id', models.CharField(blank=True, help_text='OVH order ID once order is placed', max_length=255, null=True)),
                ('ovh_cart_id', models.CharField(blank=True, help_text='OVH cart ID used for the order', max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in EUR', max_digits=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('configuring_dns', 'Configuring DNS'), ('active', 'Active'), ('dns_error', 'DNS Configuration Error'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('payment_url', models.URLField(blank=True, help_text='Mock payment URL', null=True)),
                ('dns_configuration', models.JSONField(blank=True, default=dict, help_text='JSON field to store DNS configuration details')),
                ('error_message', models.TextField(blank=True, help_text='Error message if DNS configuration fails', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who ordered the domain', on_delete=django.db.models.deletion.CASCADE, related_name='domain_orders', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(help_text='The site this domain is for', on_delete=django.db.models.deletion.CASCADE, related_name='domain_orders', to='api.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
