# Generated by Django 5.2.1 on 2025-11-27 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('terms', 'Regulamin'), ('policy', 'Polityka Prywatności'), ('guide', 'Poradnik')], default='terms', help_text='Type of legal document', max_length=20)),
                ('version', models.CharField(default='0.0', help_text="Version number, e.g., '1.0' or '2025-11-01'", max_length=20)),
                ('content_md', models.TextField(blank=True, default='', help_text='Markdown content of the document')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('document_type', 'version')},
            },
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='terms_agreement',
            field=models.ForeignKey(blank=True, help_text='The ToS version this user has accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreed_users', to='api.legaldocument'),
        ),
        migrations.DeleteModel(
            name='TermsOfService',
        ),
    ]
