# Generated by Django 5.2.1 on 2025-11-22 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('studio_editor', 'Studio Editor'), ('studio_events', 'Studio Events'), ('studio_dashboard', 'Studio Dashboard'), ('studio_team', 'Studio Team'), ('other', 'Other')], default='studio_editor', help_text='Context/section where the message was sent', max_length=50)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context data (page_id, module_id, etc.)')),
                ('user_message', models.TextField(help_text='Message sent by the user')),
                ('ai_response', models.TextField(help_text='Response from AI assistant')),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID for tracking', max_length=100, null=True)),
                ('status', models.CharField(default='success', help_text='Status of the AI response (success, error, clarification)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, help_text='Site context for the message (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='api.site')),
                ('user', models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_chathis_user_id_b3b27a_idx'), models.Index(fields=['site', '-created_at'], name='api_chathis_site_id_b364be_idx'), models.Index(fields=['context_type', '-created_at'], name='api_chathis_context_2bcf35_idx')],
            },
        ),
    ]
