# Generated by Django 5.2.1 on 2025-11-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_legaldocument_alter_platformuser_terms_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainorder',
            name='domain_expiration_date',
            field=models.DateField(blank=True, help_text='Domain expiration date from registrar (e.g., from WHOIS lookup)', null=True),
        ),
        migrations.AddField(
            model_name='domainorder',
            name='expiration_email_sent',
            field=models.BooleanField(default=False, help_text='Whether the 1-week expiration email was sent'),
        ),
        migrations.AddField(
            model_name='domainorder',
            name='expiration_notification_sent',
            field=models.BooleanField(default=False, help_text='Whether the 1-month expiration notification was sent'),
        ),
    ]
