# Generated by Django 5.2.1 on 2025-11-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_user_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuser',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, help_text='User preferences: {"theme": {"mode": "dark", "themeId": "studio"}, "calendar": {"operating_start_hour": 6, "operating_end_hour": 22}}'),
        ),
    ]
