# Generated by Django 5.2.1 on 2025-11-22 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chathistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_type', models.CharField(choices=[('studio_editor', 'Studio Editor'), ('studio_events', 'Studio Events'), ('studio_dashboard', 'Studio Dashboard'), ('studio_team', 'Studio Team'), ('other', 'Other')], default='studio_editor', help_text='Context/section where this agent operates', max_length=50)),
                ('name', models.CharField(help_text='Agent name (e.g., "Asystent #1", "Events Helper")', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(help_text='Site this agent is working on', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='api.site')),
                ('user', models.ForeignKey(help_text='User who owns this agent', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chathistory',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent that handled this conversation', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='api.agent'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['agent', '-created_at'], name='api_chathis_agent_i_8dfb3a_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['user', 'site', 'context_type'], name='api_agent_user_id_333fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['user', '-created_at'], name='api_agent_user_id_96b225_idx'),
        ),
    ]
