# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_site_is_mock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='assigned_to_team_member',
            field=models.ForeignKey(
                blank=True, 
                help_text='Team member assigned to this event', 
                null=True, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='assigned_events', 
                to='api.teammember'
            ),
        ),
    ]
