# Generated by Django 5.2.1 on 2025-11-19 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_domainorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainorder',
            name='target',
            field=models.CharField(blank=True, help_text='Target URL for domain redirect (e.g., youtube.com or user site subdomain)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='domainorder',
            name='dns_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='DNS records configured for this domain'),
        ),
        migrations.AlterField(
            model_name='domainorder',
            name='domain_name',
            field=models.CharField(help_text='Full domain name (e.g., example.com)', max_length=255),
        ),
        migrations.AlterField(
            model_name='domainorder',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if DNS configuration failed', null=True),
        ),
        migrations.AlterField(
            model_name='domainorder',
            name='ovh_cart_id',
            field=models.CharField(blank=True, help_text='OVH cart ID used for this order', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='domainorder',
            name='ovh_order_id',
            field=models.CharField(blank=True, help_text='OVH order ID from the API', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='domainorder',
            name='payment_url',
            field=models.URLField(blank=True, help_text='Mock payment URL for testing', null=True),
        ),
        migrations.AlterField(
            model_name='domainorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Domain price in EUR', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='domainorder',
            name='site',
            field=models.ForeignKey(help_text='Site this domain is for', on_delete=django.db.models.deletion.CASCADE, related_name='domain_orders', to='api.site'),
        ),
        migrations.AlterField(
            model_name='domainorder',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('configuring_dns', 'Configuring DNS'), ('active', 'Active'), ('dns_error', 'DNS Configuration Error'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_payment', help_text='Current status of the domain order', max_length=32),
        ),
        migrations.AlterField(
            model_name='domainorder',
            name='user',
            field=models.ForeignKey(help_text='User who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='domain_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='domainorder',
            index=models.Index(fields=['user', 'status'], name='api_domaino_user_id_8076ca_idx'),
        ),
        migrations.AddIndex(
            model_name='domainorder',
            index=models.Index(fields=['site'], name='api_domaino_site_id_e7d8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='domainorder',
            index=models.Index(fields=['ovh_order_id'], name='api_domaino_ovh_ord_285d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='domainorder',
            index=models.Index(fields=['domain_name'], name='api_domaino_domain__720902_idx'),
        ),
    ]
