# Generated by Django 5.2.1 on 2025-11-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attendedsession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendedsession',
            new_name='api_attende_site_id_6b10e2_idx',
            old_name='api_attende_site_id_ho_b707d0_idx',
        ),
        migrations.RenameIndex(
            model_name='attendedsession',
            new_name='api_attende_start_t_09867f_idx',
            old_name='api_attende_start_ti_84e1ae_idx',
        ),
    ]
