# Generated by Django 5.2.1 on 2025-11-22 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agent_chathistory_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this agent is working on (optional for global agents)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='api.site'),
        ),
    ]
