# Generated by Django 5.2.1 on 2025-10-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_availabilityblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='avatar',
            field=models.CharField(blank=True, help_text='URL to user avatar image', max_length=500, null=True),
        ),
    ]
