# Generated by Django 5.2.1 on 2025-11-03 19:36

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_platformuser_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text="Version number, e.g., '1.0' or '2025-11-01'", max_length=20, unique=True)),
                ('file', models.FileField(help_text='The PDF file for these terms.', upload_to=api.models.terms_of_service_path)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddField(
            model_name='platformuser',
            name='terms_agreement_date',
            field=models.DateTimeField(blank=True, help_text='When the user accepted the ToS', null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='terms_agreement',
            field=models.ForeignKey(blank=True, help_text='The ToS version this user has accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreed_users', to='api.termsofservice'),
        ),
    ]
