# Generated by Django 5.2.1 on 2025-11-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_domainorder_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainorder',
            name='proxy_mode',
            field=models.BooleanField(default=False, help_text='If True, use reverse proxy (keeps URL). If False, use 301 redirect (changes URL)'),
        ),
    ]
