# Generated by Django 5.2.1 on 2025-11-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_pexels_search_fields'),
        ('api', '0004_alter_agent_site'),
    ]

    operations = [
    ]
