# Generated by Django 5.2.1 on 2025-11-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_proxy_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclink',
            name='team_member',
            field=models.ForeignKey(blank=True, help_text='Team member associated with this invitation link', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_links', to='api.teammember'),
        ),
        migrations.AlterField(
            model_name='magiclink',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('password_reset', 'Password Reset'), ('team_invitation', 'Team Invitation')], default='login', max_length=20),
        ),
    ]
