# Generated by Django 5.2.1 on 2025-11-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20251122_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ai_checkpoints',
            field=models.JSONField(blank=True, default=list, help_text='List of AI checkpoints with {id, timestamp, config, message} for undo functionality'),
        ),
    ]
