# Generated by Django 5.2.1 on 2025-11-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_magiclink_team_member_alter_magiclink_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformuser',
            name='source_tag',
            field=models.CharField(choices=[('JACEK', 'Jacek Campaign'), ('WEB', 'Organic Web'), ('TEAM_INV', 'Team Invitation')], default='WEB', max_length=10),
        ),
    ]
