# Generated by Django 5.2.1 on 2025-11-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_magiclink'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsofservice',
            name='content_md',
            field=models.TextField(blank=True, default='', help_text='Markdown content of the terms'),
        ),
    ]
