# Generated by Django 5.2.1 on 2025-11-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_platformuser_source_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='public_image_url',
            field=models.CharField(blank=True, help_text='Public image URL displayed on site', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='avatar_url',
            field=models.CharField(blank=True, help_text='Private avatar URL for internal use', max_length=500, null=True),
        ),
    ]
