# Generated by Django 5.2.1 on 2025-10-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mediaasset_mediausage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='Size in bytes of the stored media file'),
        ),
    ]
