# Generated by Django 5.2.1 on 2025-11-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_site_ai_checkpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='deleted',
            field=models.BooleanField(default=False, help_text='Whether this message was deleted/reverted by user'),
        ),
    ]
