# Generated by Django 5.2.1 on 2025-10-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_mediaasset_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='storage_bucket',
            field=models.CharField(blank=True, default='', help_text='Supabase bucket name (if applicable)', max_length=100),
        ),
    ]
