# Generated by Django 5.2.1 on 2025-11-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_teammember_public_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Biography displayed on team page', null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='public_image_url',
            field=models.CharField(blank=True, help_text='Public image URL displayed on team page', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='role_description',
            field=models.CharField(blank=True, help_text='Role/title displayed on team page (e.g., "Założyciel", "Instruktor")', max_length=200, null=True),
        ),
    ]
