# Generated by Django 5.2.1 on 2025-11-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chathistory_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigevent',
            name='ai_checkpoints',
            field=models.JSONField(blank=True, default=list, help_text='List of AI checkpoints (max 20, newest first). Each checkpoint stores event state before AI changes.'),
        ),
    ]
