# Generated by Django 5.2.1 on 2025-11-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_platformuser_bio_platformuser_public_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='invitation_status',
            field=models.CharField(choices=[('invited', 'Invited (No account)'), ('pending', 'Pending (Has account)'), ('linked', 'Linked (Connected)'), ('rejected', 'Rejected/Left')], default='invited', max_length=16),
        ),
    ]
