# Generated by Django 5.2.1 on 2025-10-27 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mediaasset_storage_bucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('achievement', 'Achievement'), ('cancellation', 'Cancellation'), ('group_full', 'Group Full'), ('other', 'Other')], default='other', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='mediaasset',
            new_name='api_mediaas_media_t_b488c2_idx',
            old_name='api_mediaas_media_t_e252e3_idx',
        ),
        migrations.RenameIndex(
            model_name='mediaasset',
            new_name='api_mediaas_uploade_4e60c9_idx',
            old_name='api_mediaas_upload_0ebc36_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
