# Generated by Django 5.2.1 on 2025-11-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bigevent_ai_checkpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='related_event_id',
            field=models.IntegerField(blank=True, help_text='ID of BigEvent created/modified by this AI response (for undo functionality)', null=True),
        ),
    ]
