# Generated by Django 5.2.1 on 2025-11-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chathistory_related_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainorder',
            name='cloudflare_nameservers',
            field=models.JSONField(blank=True, default=list, help_text='Cloudflare nameservers assigned to this domain'),
        ),
        migrations.AddField(
            model_name='domainorder',
            name='cloudflare_zone_id',
            field=models.CharField(blank=True, help_text='Cloudflare Zone ID for this domain', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='domainorder',
            name='status',
            field=models.CharField(choices=[('free', 'Free (Not Added to Cloudflare)'), ('pending', 'Pending Nameserver Update'), ('pending_payment', 'Pending Payment'), ('configuring_dns', 'Configuring DNS'), ('active', 'Active'), ('dns_error', 'DNS Configuration Error'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('error', 'Configuration Error')], default='pending_payment', help_text='Current status of the domain order', max_length=32),
        ),
    ]
