# Generated by Django 5.2.1 on 2025-11-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_siteversion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailtemplate',
            new_name='api_emailte_owner_i_7327e9_idx',
            old_name='api_emailte_owner_i_7f3f4f_idx',
        ),
        migrations.RenameIndex(
            model_name='emailtemplate',
            new_name='api_emailte_slug_f862f4_idx',
            old_name='api_emailte_slug_a4b5c6_idx',
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='version',
            field=models.CharField(default='0.0', help_text="Version number, e.g., '1.0' or '2025-11-01'", max_length=20, unique=True),
        ),
    ]
