# Generated by Django 5.2.1 on 2025-11-23 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_domainorder_cloudflare_nameservers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainorder',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Site this domain is for (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_orders', to='api.site'),
        ),
    ]
