# Generated by Django 5.2.1 on 2025-11-20 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_convert_mock_to_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilityblock',
            name='assigned_to_owner',
            field=models.ForeignKey(blank=True, help_text='Owner assigned to this availability block', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_availability_blocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availabilityblock',
            name='assigned_to_team_member',
            field=models.ForeignKey(blank=True, help_text='Team member assigned to this availability block', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_availability_blocks', to='api.teammember'),
        ),
        migrations.AddField(
            model_name='availabilityblock',
            name='show_host',
            field=models.BooleanField(default=False, help_text='Whether to display the host/assigned person publicly'),
        ),
        migrations.AddField(
            model_name='event',
            name='show_host',
            field=models.BooleanField(default=False, help_text='Whether to display the host/assigned person publicly'),
        ),
        migrations.AddConstraint(
            model_name='availabilityblock',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_to_owner__isnull', True), ('assigned_to_team_member__isnull', True)), models.Q(('assigned_to_owner__isnull', True), ('assigned_to_team_member__isnull', False)), models.Q(('assigned_to_owner__isnull', False), ('assigned_to_team_member__isnull', True)), _connector='OR'), name='availability_optional_single_assignment'),
        ),
    ]
