# Generated by Django 5.2.1 on 2025-11-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_domainorder_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigevent',
            name='send_email_on_publish',
        ),
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='domainorder',
            name='status',
            field=models.CharField(choices=[('free', 'Added to Cloudflare - Awaiting Configuration'), ('pending', 'Waiting for Nameserver Propagation'), ('pending_payment', 'Pending Payment'), ('configuring_dns', 'Configuring DNS'), ('active', 'Active'), ('dns_error', 'DNS Configuration Error'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('error', 'Configuration Error')], default='pending_payment', help_text='Current status of the domain order', max_length=32),
        ),
    ]
