# Generated by Django 5.2.1 on 2025-11-20 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_convert_mock_to_invited'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='AI-generated summary of recent testimonials')),
                ('detailed_summary', models.TextField(blank=True, help_text='Detailed AI-generated analysis for admin panel')),
                ('total_count', models.IntegerField(default=0, help_text='Total number of testimonials analyzed')),
                ('average_rating', models.FloatField(default=0.0, help_text='Average rating from analyzed testimonials')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(help_text='Site this summary belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_summary', to='api.site')),
            ],
            options={
                'verbose_name_plural': 'Testimonial summaries',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Name of the person leaving the testimonial', max_length=255)),
                ('author_email', models.EmailField(blank=True, help_text='Email address (optional, for verification)', max_length=254, null=True)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5')),
                ('content', models.TextField(help_text='Testimonial content')),
                ('is_approved', models.BooleanField(default=True, help_text='Whether this testimonial is approved for public display')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(help_text='Site this testimonial belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='api.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', 'is_approved'], name='api_testimo_site_id_a73bd6_idx'), models.Index(fields=['site', 'rating'], name='api_testimo_site_id_b049c6_idx'), models.Index(fields=['created_at'], name='api_testimo_created_73c6da_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='testimonial_rating_range')],
            },
        ),
    ]
