# Generated by Django 5.2.1 on 2025-11-14 13:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_avatar_to_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assigned_to_owner',
            field=models.ForeignKey(blank=True, help_text='Owner assigned to this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site',
            name='team_size',
            field=models.IntegerField(default=1, help_text='Cached count of team members for calendar optimization'),
        ),
        migrations.AlterField(
            model_name='platformuser',
            name='account_type',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('pro_plus', 'Pro+')], default='free', max_length=10),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, help_text='Required for sending invitations', max_length=254, null=True)),
                ('role_description', models.CharField(blank=True, help_text='E.g., "Yoga Instructor", "Therapist"', max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Member bio for public display')),
                ('avatar_url', models.CharField(blank=True, help_text='Custom avatar URL or null for generated', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invitation_status', models.CharField(choices=[('mock', 'Mock (Not invited)'), ('invited', 'Invited (No account)'), ('pending', 'Pending (Has account)'), ('linked', 'Linked (Connected)'), ('rejected', 'Rejected/Left')], default='mock', max_length=16)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('permission_role', models.CharField(choices=[('viewer', 'Viewer'), ('contributor', 'Contributor'), ('manager', 'Manager')], default='viewer', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='api.site')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='assigned_to_team_member',
            field=models.ForeignKey(blank=True, help_text='Team member assigned to this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_events', to='api.teammember'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assigned_to_owner__isnull', True), ('assigned_to_team_member__isnull', False)), models.Q(('assigned_to_owner__isnull', False), ('assigned_to_team_member__isnull', True)), _connector='OR'), name='event_single_assignment'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['site', 'linked_user'], name='api_teammem_site_id_04cb88_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['invitation_token'], name='api_teammem_invitat_274d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['email'], name='api_teammem_email_fc2829_idx'),
        ),
    ]
