# Generated by Django 5.2.1 on 2025-11-20 20:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_testimonialsummary_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session ID for this transaction (order ID)', max_length=100, unique=True)),
                ('amount', models.IntegerField(help_text='Amount in grosz (1 PLN = 100 grosz)')),
                ('currency', models.CharField(default='PLN', help_text='Currency code (ISO 4217)', max_length=3)),
                ('description', models.CharField(help_text='Payment description', max_length=255)),
                ('email', models.EmailField(help_text='Customer email', max_length=254)),
                ('plan_id', models.CharField(blank=True, help_text='Plan ID being purchased (free, pro, pro-plus)', max_length=50, null=True)),
                ('token', models.CharField(blank=True, help_text='Payment token from Przelewy24', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current payment status', max_length=20)),
                ('p24_order_id', models.CharField(blank=True, help_text='Przelewy24 order ID (returned after payment)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_payment_user_id_bab04b_idx'), models.Index(fields=['session_id'], name='api_payment_session_9cfe35_idx'), models.Index(fields=['status'], name='api_payment_status_c61efc_idx')],
            },
        ),
    ]
