# Generated by Django 5.2.1 on 2025-11-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_availabilityblock_assigned_to_owner_and_more'),
        ('api', '0012_testimonialsummary_testimonial'),
    ]

    operations = [
    ]
