# Generated by Django 5.2.1 on 2025-11-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_bigevent_send_email_on_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='category',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('session_cancelled_by_creator', 'Session Cancelled by Creator'), ('dev', 'Development/Testing')], help_text='Template category', max_length=50),
        ),
    ]
