# Generated by Django 5.2.1 on 2025-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20251120_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='is_temporary_password',
            field=models.BooleanField(default=False, help_text='Whether the user has a temporary password that must be changed'),
        ),
        migrations.AddField(
            model_name='platformuser',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='When the user last changed their password', null=True),
        ),
    ]
