# Generated by Django 5.2.1 on 2025-11-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_payment'),
        ('api', '0014_add_temporary_password_fields'),
    ]

    operations = [
    ]
