# Generated by Django 5.2.1 on 2025-11-20 22:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_temporary_password_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('frequency', models.CharField(choices=[('daily', 'Codziennie'), ('weekly', 'Raz w tygodniu'), ('monthly', 'Raz w miesiącu')], default='weekly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('unsubscribe_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscriptions', to='api.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'is_active'], name='api_newslet_site_id_098b7b_idx'), models.Index(fields=['unsubscribe_token'], name='api_newslet_unsubsc_caab5d_idx')],
                'unique_together': {('site', 'email')},
            },
        ),
    ]
