# Generated by Django 5.2.1 on 2025-11-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_site_publication_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainorder',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration time for domain reservation (48h from creation if not configured)', null=True),
        ),
        migrations.AlterField(
            model_name='domainorder',
            name='status',
            field=models.CharField(choices=[('free', 'Added to Cloudflare - Awaiting Configuration'), ('pending', 'Waiting for Nameserver Propagation'), ('pending_payment', 'Pending Payment'), ('configuring_dns', 'Configuring DNS'), ('active', 'Active'), ('dns_error', 'DNS Configuration Error'), ('expired', 'Expired (Not Configured in Time)'), ('cancelled', 'Cancelled'), ('error', 'Configuration Error')], default='pending_payment', help_text='Current status of the domain order', max_length=32),
        ),
        migrations.AlterField(
            model_name='site',
            name='subdomain',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated subdomain (e.g., 1234-nazwa.youreasysite.pl)', max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='domainorder',
            index=models.Index(fields=['expires_at'], name='api_domaino_expires_528b93_idx'),
        ),
        migrations.AddConstraint(
            model_name='domainorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['free', 'pending', 'configuring_dns', 'active'])), fields=('domain_name',), name='unique_active_domain_per_system'),
        ),
    ]
