# Generated by Django 5.2.1 on 2025-11-26 13:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_domain_uniqueness_and_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.EmailField(help_text='Google account email', max_length=254)),
                ('access_token', models.TextField(help_text='OAuth access token (encrypted)')),
                ('refresh_token', models.TextField(help_text='OAuth refresh token (encrypted)')),
                ('token_expires_at', models.DateTimeField(help_text='When the access token expires')),
                ('calendar_id', models.CharField(help_text='Google Calendar ID (usually the email)', max_length=255)),
                ('calendar_name', models.CharField(blank=True, help_text='Display name of the calendar', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether sync is currently active')),
                ('sync_enabled', models.BooleanField(default=True, help_text='Whether to sync events to Google Calendar')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, help_text='User who connected this Google Calendar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_google_calendars', to=settings.AUTH_USER_MODEL)),
                ('site', models.OneToOneField(help_text='Site connected to Google Calendar', on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_integration', to='api.site')),
            ],
            options={
                'verbose_name': 'Google Calendar Integration',
                'verbose_name_plural': 'Google Calendar Integrations',
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(help_text='Google Calendar event ID', max_length=255)),
                ('last_synced_at', models.DateTimeField(auto_now=True, help_text='Last sync timestamp')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.OneToOneField(help_text='Local event', on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_event', to='api.event')),
                ('integration', models.ForeignKey(help_text='Google Calendar integration', on_delete=django.db.models.deletion.CASCADE, related_name='synced_events', to='api.googlecalendarintegration')),
            ],
            options={
                'verbose_name': 'Google Calendar Event',
                'verbose_name_plural': 'Google Calendar Events',
            },
        ),
        migrations.AddIndex(
            model_name='googlecalendarintegration',
            index=models.Index(fields=['site', 'is_active'], name='api_googlec_site_id_3e77cf_idx'),
        ),
        migrations.AddIndex(
            model_name='googlecalendarevent',
            index=models.Index(fields=['integration', 'google_event_id'], name='api_googlec_integra_4eb0b8_idx'),
        ),
    ]
