# Generated by Django 5.2.1 on 2025-11-20 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_newslettersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_token', models.CharField(editable=False, max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='confirmation_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='emails_clicked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='emails_opened',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='emails_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='newslettersubscription',
            index=models.Index(fields=['confirmation_token'], name='api_newslet_confirm_6c4238_idx'),
        ),
        migrations.AddField(
            model_name='newsletteranalytics',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='api.newslettersubscription'),
        ),
        migrations.AddIndex(
            model_name='newsletteranalytics',
            index=models.Index(fields=['tracking_token'], name='api_newslet_trackin_a71651_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletteranalytics',
            index=models.Index(fields=['subscription', 'sent_at'], name='api_newslet_subscri_17368c_idx'),
        ),
    ]
