# Generated by Django 5.2.1 on 2025-11-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_0013_payment_0014_add_temporary_password_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='event_capacity_positive',
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Maximum capacity. Null for unlimited participants.', null=True),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1), ('capacity__isnull', True), _connector='OR'), name='event_capacity_positive_or_null'),
        ),
    ]
