# Generated by Django 5.2.1 on 2025-11-20 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_payment'),
        ('api', '0016_newsletter_double_optin_analytics'),
    ]

    operations = [
    ]
