# Generated by Django 5.2.1 on 2025-11-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_event_event_capacity_positive_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='event_capacity_positive_or_null',
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=1, help_text='Maximum capacity. Use -1 for unlimited participants.'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 1), ('capacity', -1), _connector='OR'), name='event_capacity_positive_or_unlimited'),
        ),
    ]
