from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .payment_views import (
    create_payment,
    payment_webhook,
    payment_status,
    payment_history,
)
from .views import (
    PlatformUserViewSet,
    SiteViewSet,
    ClientViewSet,
    EventViewSet,
    BookingViewSet,
    CustomRegisterView,
    ResendVerificationEmailView,
    ConfirmEmailView,
    RequestMagicLinkView,
    VerifyMagicLinkView,
    RequestPasswordResetView,
    VerifyPasswordResetTokenView,
    ChangePasswordView,
    GoogleLogin,
    TemplateViewSet,
    PublicSiteListView,
    PublicSiteView,
    PublicSiteByIdView,
    PublicTeamView,
    demo_config_view,
    publish_site,
    FileUploadView,
    CustomReactComponentViewSet,
    NotificationViewSet,
    AvailabilityBlockViewSet,
    SendEmailView,
    AdminSessionCancellationEmailView,
    AdminSessionNewReservationEmailView,
    SessionCanceledByAdminEmailView,
    SessionConfirmedDiscordEmailView,
    SessionConfirmedGoogleMeetEmailView,
    SessionNewReservationEmailView,
    LatestTermsView,
    AcceptTermsView,
    AllTermsView,
    CreateTermsView,
    AdminUsersListView,
    AdminSitesListView,
    EmailTemplateViewSet,
    UserEmailsViewSet,
    SendTestEmailView,
    PublicBookingView,
    PublicAvailabilityView,
    TeamMemberViewSet,
    accept_invitation,
    accept_invitation_studio,
    reject_invitation_studio,
    check_domain_availability,
    purchase_domain,
    confirm_domain_payment,
    get_domain_orders,
    update_domain_order,
    ovh_payment_webhook,
    check_order_status,
    get_order_history,
    retry_dns_configuration,
    get_domain_pricing,
    get_cloudflare_nameservers,
    track_domain_status,
    add_domain_with_cloudflare,
    AITaskView,
    poll_ai_task_result,
    resolve_domain,
    validate_setup_token,
    setup_account,
    TestimonialViewSet,
    newsletter_subscribe,
    newsletter_unsubscribe,
    newsletter_confirm,
    newsletter_track_open,
    newsletter_track_click,
    newsletter_stats,
    AttendanceReportView,
    BigEventViewSet,
    public_big_events,
    get_chat_history,
    reset_chat_history,
    mark_chat_messages_deleted,
    update_chat_history,
    agent_list,
    agent_detail,
    pexels_search_images,
    pexels_quota,
    create_checkpoint,
    restore_checkpoint,
    list_checkpoints,
    create_event_checkpoint,
    restore_event_checkpoint,
    list_event_checkpoints,
)


router = DefaultRouter()
router.register(r'users', PlatformUserViewSet, basename='user')
router.register(r'sites', SiteViewSet, basename='site')
router.register(r'clients', ClientViewSet, basename='client')
router.register(r'events', EventViewSet, basename='event')
router.register(r'bookings', BookingViewSet, basename='booking')
router.register(r'templates', TemplateViewSet, basename='template')
router.register(r'custom-components', CustomReactComponentViewSet, basename='customcomponent')
router.register(r'notifications', NotificationViewSet, basename='notification')
router.register(r'availability-blocks', AvailabilityBlockViewSet, basename='availabilityblock')
router.register(r'email-templates', EmailTemplateViewSet, basename='emailtemplate')
router.register(r'user-emails', UserEmailsViewSet, basename='useremail')
router.register(r'team-members', TeamMemberViewSet, basename='teammember')
router.register(r'testimonials', TestimonialViewSet, basename='testimonial')
router.register(r'big-events', BigEventViewSet, basename='bigevent')

urlpatterns = [
    path('', include(router.urls)),
    path('auth/register/', CustomRegisterView.as_view(), name='custom_register'),
    path('auth/resend-verification/', ResendVerificationEmailView.as_view(), name='resend_verification'),
    path('auth/confirm-email/', ConfirmEmailView.as_view(), name='confirm_email'),
    path('auth/magic-link/request/', RequestMagicLinkView.as_view(), name='request_magic_link'),
    path('auth/magic-link/verify/', VerifyMagicLinkView.as_view(), name='verify_magic_link'),
    path('auth/password-reset/request/', RequestPasswordResetView.as_view(), name='request_password_reset'),
    path('auth/password-reset/verify/', VerifyPasswordResetTokenView.as_view(), name='verify_password_reset'),
    path('auth/change-password/', ChangePasswordView.as_view(), name='change_password'),
    path('auth/google/', GoogleLogin.as_view(), name='google_login'),
    path('public-sites/', PublicSiteListView.as_view(), name='public_sites_list'),
    path('public-sites/by-id/<int:site_id>/', PublicSiteByIdView.as_view(), name='public_site_detail_by_id'),
    path('public-sites/<slug:identifier>/', PublicSiteView.as_view(), name='public_site_detail'),
    path('demo-config/', demo_config_view, name='demo_config'),
    path('sites/<int:site_id>/publish/', publish_site, name='publish-site'),
    path('upload/', FileUploadView.as_view(), name='file-upload'),
    path('send-custom-email/', SendEmailView.as_view(), name='send-custom-email'),
    path('emails/test/', SendTestEmailView.as_view(), name='send-test-email'),
    path('emails/admin-session-cancellation/', AdminSessionCancellationEmailView.as_view(), name='email-admin-session-cancellation'),
    path('emails/admin-session-new-reservation/', AdminSessionNewReservationEmailView.as_view(), name='email-admin-session-new-reservation'),
    path('emails/session-canceled-by-admin/', SessionCanceledByAdminEmailView.as_view(), name='email-session-canceled-by-admin'),
    path('emails/session-confirmed-discord/', SessionConfirmedDiscordEmailView.as_view(), name='email-session-confirmed-discord'),
    path('emails/session-confirmed-google-meet/', SessionConfirmedGoogleMeetEmailView.as_view(), name='email-session-confirmed-google-meet'),
    path('emails/session-new-reservation/', SessionNewReservationEmailView.as_view(), name='email-session-new-reservation'),
    path('terms/latest/', LatestTermsView.as_view(), name='terms-latest'),
    path('terms/accept/', AcceptTermsView.as_view(), name='terms-accept'),
    path('terms/all/', AllTermsView.as_view(), name='terms-all'),
    path('terms/create/', CreateTermsView.as_view(), name='terms-create'),
    path('admin/users/', AdminUsersListView.as_view(), name='admin-users-list'),
    path('admin/sites/', AdminSitesListView.as_view(), name='admin-sites-list'),
    path('public-sites/<int:site_id>/bookings/', PublicBookingView.as_view(), name='public_booking'),
    path('public-sites/<int:site_id>/availability/', PublicAvailabilityView.as_view(), name='public_availability'),
    path('public-sites/<int:site_id>/team/', PublicTeamView.as_view(), name='public_team'),
    path('sites/<int:site_id>/attendance-report/', AttendanceReportView.as_view(), name='attendance-report'),
    # Team invitation endpoints
    path('accept-invitation/<uuid:token>/', accept_invitation, name='accept-invitation'),
    path('team-invitations/<uuid:token>/accept/', accept_invitation_studio, name='accept-invitation-studio'),
    path('team-invitations/<uuid:token>/reject/', reject_invitation_studio, name='reject-invitation-studio'),
    # Account setup (new team members)
    path('validate-setup-token/<str:token>/', validate_setup_token, name='validate-setup-token'),
    path('setup-account/<str:token>/', setup_account, name='setup-account'),
    # Domain checking endpoints
    path('domains/check-availability/', check_domain_availability, name='check-domain-availability'),
    path('domains/purchase/', purchase_domain, name='purchase-domain'),
    path('domains/confirm-payment/', confirm_domain_payment, name='confirm-domain-payment'),
    path('domains/orders/', get_domain_orders, name='get-domain-orders'),
    path('domains/orders/<int:order_id>/', update_domain_order, name='update-domain-order'),
    path('domains/orders/<int:order_id>/history/', get_order_history, name='get-order-history'),
    path('domains/webhook/ovh/', ovh_payment_webhook, name='ovh-payment-webhook'),
    path('domains/check-status/', check_order_status, name='check-order-status'),
    path('domains/retry-dns/', retry_dns_configuration, name='retry-dns-configuration'),
    path('domains/pricing/', get_domain_pricing, name='get-domain-pricing'),
    path('domains/resolve/<str:domain>/', resolve_domain, name='resolve-domain'),
    path('domains/nameservers/', get_cloudflare_nameservers, name='get-cloudflare-nameservers'),
    path('domains/track-status/', track_domain_status, name='track-domain-status'),
    path('domains/add/', add_domain_with_cloudflare, name='add-domain-cloudflare'),
    # AI Assistant endpoints
    path('ai-task/', AITaskView.as_view(), name='ai-task'),
    path('ai-task/<str:task_id>/poll/', poll_ai_task_result, name='poll-ai-task'),
    path('agents/', agent_list, name='agent-list'),
    path('agents/<uuid:agent_id>/', agent_detail, name='agent-detail'),
    path('chat/history/', get_chat_history, name='get-chat-history'),
    path('chat/history/<int:message_id>/', update_chat_history, name='update-chat-history'),
    path('chat/reset/', reset_chat_history, name='reset-chat-history'),
    path('chat/mark-deleted/', mark_chat_messages_deleted, name='mark-chat-messages-deleted'),
    # AI Checkpoint endpoints
    path('sites/<int:site_id>/checkpoints/', create_checkpoint, name='create-checkpoint'),
    path('sites/<int:site_id>/checkpoints/restore/<str:checkpoint_id>/', restore_checkpoint, name='restore-checkpoint'),
    path('sites/<int:site_id>/checkpoints/list/', list_checkpoints, name='list-checkpoints'),
    # BigEvent AI Checkpoint endpoints
    path('big-events/<int:event_id>/checkpoints/', create_event_checkpoint, name='create-event-checkpoint'),
    path('big-events/<int:event_id>/checkpoints/restore/<str:checkpoint_id>/', restore_event_checkpoint, name='restore-event-checkpoint'),
    path('big-events/<int:event_id>/checkpoints/list/', list_event_checkpoints, name='list-event-checkpoints'),
    # Newsletter endpoints
    path('newsletter/subscribe/', newsletter_subscribe, name='newsletter-subscribe'),
    path('newsletter/unsubscribe/<str:token>/', newsletter_unsubscribe, name='newsletter-unsubscribe'),
    path('newsletter/confirm/<str:token>/', newsletter_confirm, name='newsletter-confirm'),
    path('newsletter/track/open/<str:token>/', newsletter_track_open, name='newsletter-track-open'),
    path('newsletter/track/click/<str:token>/', newsletter_track_click, name='newsletter-track-click'),
    path('newsletter/stats/<int:site_id>/', newsletter_stats, name='newsletter-stats'),
    path('public-sites/<slug:identifier>/big-events/', public_big_events, name='public-big-events'),
    # Payment endpoints
    path('payments/create/', create_payment, name='create-payment'),
    path('payments/webhook/', payment_webhook, name='payment-webhook'),
    path('payments/status/<str:session_id>/', payment_status, name='payment-status'),
    path('payments/history/', payment_history, name='payment-history'),
    # Pexels image search endpoints
    path('sites/<int:site_id>/images/search/', pexels_search_images, name='pexels-search'),
    path('sites/<int:site_id>/images/quota/', pexels_quota, name='pexels-quota'),
]
